{
  "swagger": "2.0",
  "info": {
    "description": "This is NemoAhn API.",
    "version": "1.0.0",
    "title": "NemoAhnAPI",
    "contact": {
      "name": "NemoAhn Thermostat API",
      "url": "http://www.raonix.com",
      "email": "raonix@raonix.co.kr"
    }
  },
  "host": "api.raonix.com",
  "basePath": "/nemoahnApi/1.0.0",
  "schemes": [
    "http"
  ],
  "paths": {
    "/thermostats/{deviceId}": {
      "get": {
        "tags": [
          "thermostat"
        ],
        "summary": "상태값 조회",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "$ref": "#/parameters/deviceIdParam"
          },
          {
            "$ref": "#/parameters/startParm"
          },
          {
            "$ref": "#/parameters/endParm"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "currentTemperature": {
                  "$ref": "#/definitions/StateValueModel"
                },
                "settingTemperature": {
                  "$ref": "#/definitions/StateValueModel"
                },
                "heatting": {
                  "$ref": "#/definitions/StateValueModel"
                }
              }
            },
            "examples": {
              "application/json": {
                "currentTemperature": {
                  "max": 32,
                  "min": 15.5,
                  "avr": 23,
                  "datas": [
                    [
                      14141234134123,
                      32
                    ],
                    [
                      14321341234234,
                      15.5
                    ],
                    [
                      14213412342134,
                      20
                    ]
                  ]
                },
                "settingTemperature": {
                  "max": 32,
                  "min": 15.5,
                  "avr": 23,
                  "datas": [
                    [
                      14141234134123,
                      32
                    ],
                    [
                      14321341234234,
                      15.5
                    ],
                    [
                      14213412342134,
                      20
                    ]
                  ]
                },
                "heatting": {
                  "max": 1,
                  "min": 0,
                  "avr": 0.7,
                  "datas": [
                    [
                      14141234134123,
                      32
                    ],
                    [
                      14321341234234,
                      15.5
                    ],
                    [
                      14213412342134,
                      20
                    ]
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Invalid Device Id supplied"
          },
          "404": {
            "description": "Thermostat not found"
          }
        }
      }
    },
    "/thermostats/{deviceId}/settingTemperature": {
      "get": {
        "tags": [
          "thermostat"
        ],
        "summary": "온도설정값 조회",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "$ref": "#/parameters/deviceIdParam"
          },
          {
            "$ref": "#/parameters/startParm"
          },
          {
            "$ref": "#/parameters/endParm"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/StateValueModel"
            },
            "examples": {
              "application/json": {
                "max": 32,
                "min": 15.5,
                "avr": 23,
                "datas": [
                  [
                    14141234134123,
                    32
                  ],
                  [
                    14321341234234,
                    15.5
                  ],
                  [
                    14213412342134,
                    20
                  ]
                ]
              }
            }
          },
          "400": {
            "description": "Invalid ID supplied"
          },
          "404": {
            "description": "Thermostat not found"
          }
        }
      }
    },
    "/thermostats/{deviceId}/currentTemperature": {
      "get": {
        "tags": [
          "thermostat"
        ],
        "summary": "현재온도값 조회",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "$ref": "#/parameters/deviceIdParam"
          },
          {
            "$ref": "#/parameters/startParm"
          },
          {
            "$ref": "#/parameters/endParm"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/StateValueModel"
            }
          },
          "400": {
            "description": "Invalid ID supplied"
          },
          "404": {
            "description": "Thermostat not found"
          }
        }
      }
    },
    "/thermostats/{deviceId}/heating": {
      "get": {
        "tags": [
          "thermostat"
        ],
        "summary": "보일러 동작 상태 조회",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "$ref": "#/parameters/deviceIdParam"
          },
          {
            "$ref": "#/parameters/startParm"
          },
          {
            "$ref": "#/parameters/endParm"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/StateValueModel"
            },
            "examples": {
              "application/json": {
                "max": 1,
                "min": 0,
                "avr": 0.56,
                "datas": [
                  [
                    14141234134123,
                    1
                  ],
                  [
                    14321341234234,
                    1
                  ],
                  [
                    14213412342134,
                    0
                  ]
                ]
              }
            }
          },
          "400": {
            "description": "Invalid ID supplied"
          },
          "404": {
            "description": "Thermostat not found"
          }
        }
      }
    }
  },
  "parameters": {
    "deviceIdParam": {
      "name": "deviceId",
      "in": "path",
      "required": true,
      "type": "string",
      "description": "Device'Id"
    },
    "startParm": {
      "name": "start",
      "in": "query",
      "type": "integer",
      "format": "int64",
      "description": "The start time for the query"
    },
    "endParm": {
      "name": "end",
      "in": "query",
      "type": "integer",
      "format": "int64",
      "description": "The end time for the query"
    }
  },
  "definitions": {
    "StateValueModel": {
      "type": "object",
      "properties": {
        "max": {
          "type": "number"
        },
        "min": {
          "type": "number"
        },
        "avr": {
          "type": "number"
        },
        "datas": {
          "type": "array",
          "items": {
            "type": "array",
            "items": [
              {
                "type": "integer"
              },
              {
                "type": "number"
              }
            ]
          }
        }
      }
    }
  }
}